name: Format
on:
  pull_request:
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  format:
    uses: martinthomson/moz-actions/.github/workflows/rustfmt.yml@da1d345c5252406d59d668041aec11aaad093985 #testing
